Prática de Machine Learning

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn import datasets
import numpy as np

In [2]:
Diagnostico = pd.read_csv('soybean.csv')
Diagnostico.head()

date plant-stand   precip  temp hail         crop-hist area-damaged  \
0  october      normal  gt-norm  norm  yes       same-lst-yr    low-areas   
1   august      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   
2     july      normal  gt-norm  norm  yes       same-lst-yr    scattered   
3     july      normal  gt-norm  norm  yes       same-lst-yr    scattered   
4  october      normal  gt-norm  norm  yes  same-lst-two-yrs    scattered   

     severity   seed-tmt germination  ... sclerotia fruit-pods fruit-spots  \
0  pot-severe       none      90-100  ...    absent       norm         dna   
1      severe  fungicide       80-89  ...    absent       norm         dna   
2      severe  fungicide       lt-80  ...    absent       norm         dna   
3      severe       none       80-89  ...    absent       norm         dna   
4  pot-severe       none       lt-80  ...    absent       norm         dna   

   seed mold-growth seed-discolor seed-size shriveling roots  \
0  norm      absent        absent      norm     absent  norm   
1  norm      absent        absent      norm     absent  norm   
2  norm      absent        absent      norm     absent  norm   
3  norm      absent        absent      norm     absent  norm   
4  norm      absent        absent      norm     absent  norm   

                   class  
0  diaporthe-stem-canker  
1  diaporthe-stem-canker  
2  diaporthe-stem-canker  
3  diaporthe-stem-canker  
4  diaporthe-stem-canker  

[5 rows x 36 columns]

In [3]:
Diagnostico.shape

(683, 36)

In [4]:
previsores = Diagnostico.iloc[:,0:35].values
classe = Diagnostico.iloc[:,35].values

In [5]:
labelencoder = LabelEncoder()
for x in range(35):
    previsores[:,x] = labelencoder.fit_transform(previsores[:,x])
previsores

array([[6, 2, 1, ..., 2, 1, 2],
       [2, 2, 1, ..., 2, 1, 2],
       [3, 2, 1, ..., 2, 1, 2],
       ...,
       [4, 1, 0, ..., 0, 0, 3],
       [1, 1, 0, ..., 0, 0, 3],
       [4, 1, 0, ..., 0, 0, 3]], dtype=object)

In [6]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

In [7]:
#Naive_bayes
naive_bayes = GaussianNB()
naive_bayes.fit(X_treinamento, y_treinamento)

GaussianNB()

In [8]:
previsoes = naive_bayes.predict(X_teste)
previsoes

array(['alternarialeaf-spot', 'phytophthora-rot', 'herbicide-injury',
       'purple-seed-stain', 'cyst-nematode', 'bacterial-blight',
       'brown-stem-rot', 'bacterial-pustule', 'brown-spot',
       'alternarialeaf-spot', 'charcoal-rot', 'bacterial-blight',
       'anthracnose', 'anthracnose', 'alternarialeaf-spot', 'brown-spot',
       'alternarialeaf-spot', 'alternarialeaf-spot',
       'rhizoctonia-root-rot', 'phytophthora-rot', 'anthracnose',
       'brown-stem-rot', 'phyllosticta-leaf-spot',
       'phyllosticta-leaf-spot', 'diaporthe-stem-canker', 'brown-spot',
       'anthracnose', 'diaporthe-stem-canker', 'bacterial-pustule',
       'phytophthora-rot', 'frog-eye-leaf-spot', 'alternarialeaf-spot',
       'phyllosticta-leaf-spot', 'frog-eye-leaf-spot',
       'frog-eye-leaf-spot', 'bacterial-pustule', 'brown-stem-rot',
       'charcoal-rot', 'brown-spot', 'alternarialeaf-spot',
       'brown-stem-rot', 'alternarialeaf-spot', 'phytophthora-rot',
       'anthracnose', 'bacterial

In [9]:
confusao = confusion_matrix(y_teste, previsoes)
confusao

array([[ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
         0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  7,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  1,  0,  5,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0

In [10]:
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.8585365853658536

In [11]:
#Random Forest
floresta = RandomForestClassifier(n_estimators = 100)
floresta.fit(X_treinamento, y_treinamento)

RandomForestClassifier()

In [12]:
previsoes = floresta.predict(X_teste)
previsoes

array(['brown-spot', 'phytophthora-rot', 'herbicide-injury',
       'purple-seed-stain', 'cyst-nematode', 'bacterial-blight',
       'brown-stem-rot', 'bacterial-pustule', 'brown-spot',
       'alternarialeaf-spot', 'charcoal-rot', 'bacterial-blight',
       'anthracnose', 'anthracnose', 'alternarialeaf-spot', 'brown-spot',
       'alternarialeaf-spot', 'alternarialeaf-spot',
       'rhizoctonia-root-rot', 'phytophthora-rot', 'anthracnose',
       'brown-stem-rot', 'brown-spot', 'phyllosticta-leaf-spot',
       'diaporthe-stem-canker', 'brown-spot', 'anthracnose',
       'diaporthe-stem-canker', 'bacterial-pustule', 'phytophthora-rot',
       'frog-eye-leaf-spot', 'alternarialeaf-spot',
       'phyllosticta-leaf-spot', 'frog-eye-leaf-spot', 'brown-spot',
       'bacterial-pustule', 'brown-stem-rot', 'charcoal-rot',
       'brown-spot', 'brown-spot', 'brown-stem-rot',
       'alternarialeaf-spot', 'phytophthora-rot', 'anthracnose',
       'bacterial-blight', '2-4-d-injury', 'alternarial

In [13]:
matriz = confusion_matrix(y_teste, previsoes)
matriz

array([[ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0

In [14]:
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.9512195121951219

In [15]:
#Vizinhança
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_treinamento, y_treinamento)

KNeighborsClassifier(n_neighbors=3)

In [16]:
previsoes = knn.predict(X_teste)
previsoes

C:\Users\joao_\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array(['brown-spot', 'phytophthora-rot', 'herbicide-injury',
       'alternarialeaf-spot', 'cyst-nematode', 'alternarialeaf-spot',
       'brown-stem-rot', 'bacterial-pustule', 'brown-spot', 'brown-spot',
       'charcoal-rot', 'bacterial-blight', 'anthracnose', 'anthracnose',
       'alternarialeaf-spot', 'brown-spot', 'alternarialeaf-spot',
       'alternarialeaf-spot', 'rhizoctonia-root-rot', 'phytophthora-rot',
       'anthracnose', 'brown-stem-rot', 'phyllosticta-leaf-spot',
       'brown-spot', 'diaporthe-stem-canker', 'brown-spot', 'anthracnose',
       'diaporthe-stem-canker', 'bacterial-pustule', 'phytophthora-rot',
       'frog-eye-leaf-spot', 'alternarialeaf-spot',
       'phyllosticta-leaf-spot', 'frog-eye-leaf-spot', 'brown-spot',
       'bacterial-blight', 'brown-stem-rot', 'charcoal-rot', 'brown-spot',
       'brown-spot', 'brown-stem-rot', 'alternarialeaf-spot',
       'phytophthora-rot', 'anthracnose', 'bacterial-blight',
       '2-4-d-injury', 'alternarialeaf-spot', '

In [17]:
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.775609756097561