Prática de Redes Neurais

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn import datasets
import numpy as np

In [2]:
Diagnostico = pd.read_csv('soybean.csv')
Diagnostico.head()
Diagnostico.shape

(683, 36)

In [3]:
previsores = Diagnostico.iloc[:,0:35].values
classe = Diagnostico.iloc[:,35].values

In [4]:
labelencoder = LabelEncoder()
for x in range(35):
    previsores[:,x] = labelencoder.fit_transform(previsores[:,x])
previsores = np.asarray(previsores).astype(np.float32)
previsores

array([[6., 2., 1., ..., 2., 1., 2.],
       [2., 2., 1., ..., 2., 1., 2.],
       [3., 2., 1., ..., 2., 1., 2.],
       ...,
       [4., 1., 0., ..., 0., 0., 3.],
       [1., 1., 0., ..., 0., 0., 3.],
       [4., 1., 0., ..., 0., 0., 3.]], dtype=float32)

In [5]:
labelencoder_Y = LabelEncoder()
classe = labelencoder_Y.fit_transform(classe)
classe = np.asarray(classe).astype(np.float32)
classe

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,  7.,  7.,  7.,
        7.,  7.,  7.,  7.,  7.,  7.,  7., 18., 18., 18., 18., 18., 18.,
       18., 18., 18., 18., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 11., 11., 11., 11.,
       11., 11., 11., 11., 11., 11.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17.,  2

In [6]:
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [7]:
unicos, quantidade = np.unique(classe, return_counts = True)
unicos

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18.], dtype=float32)

In [8]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe_dummy,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

In [9]:
# Criação da estrutura da rede neural com a classe Sequential (sequência de camadas)
modelo = Sequential()
#primeira camada oculta, 5 neuronios, 4 neuronios de entrada
modelo.add(Dense(units = 36, input_dim = 35))
#segunda camada oculta
modelo.add(Dense(units = 42))
modelo.add(Dense(units = 27))
# Função softmax porque temos um problema de classificação com mais de duas classes 
#(é gerada uma probabilidade em cada neurônio)
modelo.add(Dense(units =19 , activation = 'softmax'))

In [10]:
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 36)                1296      
                                                                 
 dense_1 (Dense)             (None, 42)                1554      
                                                                 
 dense_2 (Dense)             (None, 27)                1161      
                                                                 
 dense_3 (Dense)             (None, 19)                532       
                                                                 
Total params: 4,543
Trainable params: 4,543
Non-trainable params: 0
_________________________________________________________________


In [11]:
modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy',
               metrics = ['accuracy'])
# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(X_treinamento, y_treinamento, epochs = 1000,
           validation_data = (X_teste, y_teste))

Epoch 1/1000
15/15 [==============================] - 3s 43ms/step - loss: 3.3376 - accuracy: 0.1088 - val_loss: 2.9436 - val_accuracy: 0.2049
Epoch 2/1000
15/15 [==============================] - 0s 9ms/step - loss: 2.4902 - accuracy: 0.3201 - val_loss: 2.5268 - val_accuracy: 0.3561
Epoch 3/1000
15/15 [==============================] - 0s 9ms/step - loss: 2.1340 - accuracy: 0.3996 - val_loss: 2.2233 - val_accuracy: 0.4049
Epoch 4/1000
15/15 [==============================] - 0s 9ms/step - loss: 1.8893 - accuracy: 0.4812 - val_loss: 2.0010 - val_accuracy: 0.4390
Epoch 5/1000
15/15 [==============================] - 0s 10ms/step - loss: 1.6970 - accuracy: 0.5711 - val_loss: 1.8190 - val_accuracy: 0.4829
Epoch 6/1000
15/15 [==============================] - 0s 10ms/step - loss: 1.5374 - accuracy: 0.5711 - val_loss: 1.6494 - val_accuracy: 0.5512
Epoch 7/1000
15/15 [==============================] - 0s 9ms/step - loss: 1.3869 - accuracy: 0.6234 - val_loss: 1.5028 - val_accuracy: 0.5854
Epo

In [12]:
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

7/7 [==============================] - 0s 2ms/step


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [13]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [14]:
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 1, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,
         0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  1,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  1,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  1,  0,  2,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0

In [15]:
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.9170731707317074